"""S3-03b.8 F-4A: add org_id to assemblies

Revision ID: 637e52cfce1d
Revises: 32eda56478de
Create Date: 2025-10-20 06:10:23.974881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637e52cfce1d'
down_revision = '32eda56478de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_app_settings_org'), type_='unique')

    with op.batch_alter_table('assemblies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_assemblies_org_id'), ['org_id'], unique=False)
        batch_op.create_foreign_key(None, 'orgs', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)

    with op.batch_alter_table('assemblies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_assemblies_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_app_settings_org'), ['org_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
