"""baseline schema (clean)

Revision ID: c530304dc93c
Revises: 
Create Date: 2025-10-13 13:33:35.738159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c530304dc93c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assemblies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assembly_code', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('subcategory', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assemblies', schema=None) as batch_op:
        batch_op.create_index('ix_assemblies_category_active', [sa.literal_column('lower(category)')], unique=False, postgresql_where=sa.text('(is_active = true)'))
        batch_op.create_index('ix_assemblies_category_subcategory_active', [sa.literal_column('lower(category)'), sa.literal_column('lower(subcategory)')], unique=False, postgresql_where=sa.text('(is_active = true)'))
        batch_op.create_index('ix_assemblies_subcategory_active', [sa.literal_column('lower(subcategory)')], unique=False, postgresql_where=sa.text('(is_active = true)'))
        batch_op.create_index('uq_assemblies_lower_name_active_idx', [sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('(is_active = true)'))

    op.create_table('dje_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('default_unit_cost', sa.Numeric(precision=12, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('cost_code', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dje_items', schema=None) as batch_op:
        batch_op.create_index('ix_dje_items_cat_sub_desc', ['category', 'subcategory', 'description'], unique=False)
        batch_op.create_index('ix_dje_items_category', ['category'], unique=False)
        batch_op.create_index('ix_dje_items_lower_description', [sa.literal_column('lower(description)')], unique=False)
        batch_op.create_index('ix_dje_items_lower_description_pattern', [sa.literal_column('lower(description)')], unique=False)
        batch_op.create_index('ux_dje_items_cat_desc_vendor_active_true', ['category', 'description', 'vendor'], unique=True, postgresql_where=sa.text('(is_active = true)'))

    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('item_description', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('labor_unit', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('unit_quantity_size', sa.Integer(), nullable=False),
    sa.Column('material_cost_code', sa.Text(), nullable=True),
    sa.Column('mat_cost_code_desc', sa.Text(), nullable=True),
    sa.Column('labor_cost_code', sa.Text(), nullable=True),
    sa.Column('labor_cost_code_desc', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index('ix_materials_lower_item_description', [sa.literal_column('lower(item_description)')], unique=False)
        batch_op.create_index('ix_materials_lower_item_description_pattern', [sa.literal_column('lower(item_description)')], unique=False)
        batch_op.create_index('ix_materials_material_type', ['material_type'], unique=False)
        batch_op.create_index('ix_materials_type_active_desc', ['material_type', 'is_active', 'item_description'], unique=False)
        batch_op.create_index('ux_materials_type_desc_active_true', ['material_type', 'item_description'], unique=True, postgresql_where=sa.text('(is_active = true)'))

    op.create_table('assembly_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assembly_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty_per_assembly', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assembly_components', schema=None) as batch_op:
        batch_op.create_index('ix_ac_assembly', ['assembly_id'], unique=False)
        batch_op.create_index('ix_ac_assembly_sort', ['assembly_id', 'sort_order'], unique=False)
        batch_op.create_index('ix_ac_material', ['material_id'], unique=False)
        batch_op.create_index('uq_ac_assembly_material_active_idx', ['assembly_id', 'material_id'], unique=True, postgresql_where=sa.text('(is_active = true)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assembly_components', schema=None) as batch_op:
        batch_op.drop_index('uq_ac_assembly_material_active_idx', postgresql_where=sa.text('(is_active = true)'))
        batch_op.drop_index('ix_ac_material')
        batch_op.drop_index('ix_ac_assembly_sort')
        batch_op.drop_index('ix_ac_assembly')

    op.drop_table('assembly_components')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index('ux_materials_type_desc_active_true', postgresql_where=sa.text('(is_active = true)'))
        batch_op.drop_index('ix_materials_type_active_desc')
        batch_op.drop_index('ix_materials_material_type')
        batch_op.drop_index('ix_materials_lower_item_description_pattern')
        batch_op.drop_index('ix_materials_lower_item_description')

    op.drop_table('materials')
    with op.batch_alter_table('dje_items', schema=None) as batch_op:
        batch_op.drop_index('ux_dje_items_cat_desc_vendor_active_true', postgresql_where=sa.text('(is_active = true)'))
        batch_op.drop_index('ix_dje_items_lower_description_pattern')
        batch_op.drop_index('ix_dje_items_lower_description')
        batch_op.drop_index('ix_dje_items_category')
        batch_op.drop_index('ix_dje_items_cat_sub_desc')

    op.drop_table('dje_items')
    with op.batch_alter_table('assemblies', schema=None) as batch_op:
        batch_op.drop_index('uq_assemblies_lower_name_active_idx', postgresql_where=sa.text('(is_active = true)'))
        batch_op.drop_index('ix_assemblies_subcategory_active', postgresql_where=sa.text('(is_active = true)'))
        batch_op.drop_index('ix_assemblies_category_subcategory_active', postgresql_where=sa.text('(is_active = true)'))
        batch_op.drop_index('ix_assemblies_category_active', postgresql_where=sa.text('(is_active = true)'))

    op.drop_table('assemblies')
    # ### end Alembic commands ###
